# Generated by Django 3.2.7 on 2021-10-14 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("holiday_acres_api", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="horse",
            name="paddock",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="horses",
                to="holiday_acres_api.paddock",
            ),
        ),
        migrations.AlterField(
            model_name="horse",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="horses",
                to="holiday_acres_api.user",
            ),
        ),
    ]
