# Generated by Django 3.2.7 on 2021-10-04 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("holiday_acres_api", "0002_paddock")]

    operations = [migrations.RemoveField(model_name="paddock", name="last_maintained")]
