# Generated by Django 3.2.7 on 2021-12-10 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("holiday_acres_api", "0002_auto_20211123_2219")]

    operations = [
        migrations.CreateModel(
            name="Barn_Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(model_name="horse", name="paddock"),
        migrations.AlterField(
            model_name="user", name="email", field=models.CharField(max_length=200)
        ),
        migrations.AlterField(
            model_name="user", name="first_name", field=models.CharField(max_length=200)
        ),
        migrations.AlterField(
            model_name="user", name="last_name", field=models.CharField(max_length=200)
        ),
        migrations.AlterField(
            model_name="user", name="password", field=models.CharField(max_length=200)
        ),
        migrations.AlterField(
            model_name="user", name="username", field=models.CharField(max_length=200)
        ),
        migrations.AddField(
            model_name="horse",
            name="barn_section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="horses",
                to="holiday_acres_api.barn_section",
            ),
        ),
    ]
