# Generated by Django 3.2.7 on 2021-12-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("holiday_acres_api", "0003_auto_20211210_1037")]

    operations = [
        migrations.AddField(
            model_name="horse",
            name="stall",
            field=models.TextField(default=1),
            preserve_default=False,
        )
    ]
