# Generated by Django 3.2.7 on 2021-10-04 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("holiday_acres_api", "0003_remove_paddock_last_maintained")]

    operations = [
        migrations.RenameField(
            model_name="paddock", old_name="name", new_name="paddock_name"
        )
    ]
