# Generated by Django 3.2.7 on 2021-10-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("holiday_acres_api", "0004_rename_name_paddock_paddock_name")]

    operations = [
        migrations.AddField(
            model_name="paddock",
            name="name",
            field=models.CharField(default="no name", max_length=200),
            preserve_default=False,
        )
    ]
