# Generated by Django 3.2.7 on 2021-12-10 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("holiday_acres_api", "0005_auto_20211210_1137")]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="horse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feed",
                to="holiday_acres_api.horse",
            ),
        )
    ]
