# Generated by Django 3.2.7 on 2021-10-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("holiday_acres_api", "0005_paddock_name")]

    operations = [
        migrations.CreateModel(
            name="Horse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("paddock_name", models.CharField(max_length=200)),
                ("owner", models.CharField(max_length=200)),
                ("tier", models.IntegerField()),
                ("age", models.IntegerField()),
                ("feed", models.CharField(max_length=200)),
                ("misc_notes", models.TextField()),
                ("health", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        )
    ]
