# Generated by Django 3.2.7 on 2021-12-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("holiday_acres_api", "0007_auto_20211211_1511")]

    operations = [
        migrations.RemoveField(model_name="horse", name="age"),
        migrations.RemoveField(model_name="horse", name="health"),
        migrations.RemoveField(model_name="horse", name="misc_notes"),
        migrations.RemoveField(model_name="horse", name="tier"),
    ]
