# Generated by Django 3.2.7 on 2021-12-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("holiday_acres_api", "0008_auto_20211211_1529")]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        )
    ]
