# Generated by Django 3.2.7 on 2022-01-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holiday_acres_api", "0010_auto_20211212_2041"),
        ("holiday_acres_api", "0010_auto_20211220_2039"),
    ]

    operations = []
