# Generated by Django 3.2.11 on 2022-01-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "holiday_acres_api",
            "0011_merge_0010_auto_20211212_2041_0010_auto_20211220_2039",
        )
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SCOOP", "SCOOP"),
                    ("HANDFUL", "HANDFUL"),
                    ("FIRST_CUT", "FIRST_CUT"),
                    ("SECOND_CUT", "SECOND_CUT"),
                    ("CUP", "CUP"),
                ],
                max_length=200,
            ),
        )
    ]
