# Generated by Django 3.2.11 on 2022-06-06 10:31

from django.db import migrations


def associate_horse_photo(apps, schema_editor):
    Horse = apps.get_model("holiday_acres_api", "Horse")

    Horse.objects.filter(name="Mac").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2019/03/received_487376025211427-225x300.jpg"
    )
    Horse.objects.filter(name="Kai").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2019/03/received_471313067215090-225x300.jpg"
    )
    Horse.objects.filter(name="Shiloh").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2019/03/received_1375625739251824-225x300.jpg"
    )
    Horse.objects.filter(name="Belle").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2019/03/FB_IMG_16373346976021-300x225.jpg"
    )
    Horse.objects.filter(name="Midnight").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2019/03/FB_IMG_1637333177246-300x225.jpg"
    )
    Horse.objects.filter(name="Milo").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2019/03/FB_IMG_1637708392880-300x226.jpg"
    )
    Horse.objects.filter(name="Estrella").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2019/03/FB_IMG_1614383609599-300x292.jpg"
    )
    Horse.objects.filter(name="Clyde").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2019/03/IMG_76441-225x300.jpg"
    )
    Horse.objects.filter(name="Angel").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2019/03/received_486743649211779-225x300.jpg"
    )
    Horse.objects.filter(name="Ranger").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2019/03/received_150609883552916-300x290.jpg"
    )
    Horse.objects.filter(name="Beau").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2010/05/Beau-265x300.jpg"
    )
    Horse.objects.filter(name="Penny").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2019/03/IMG_76621-138x300.jpg"
    )
    Horse.objects.filter(name="Champ").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2010/05/Champ-300x300.jpg"
    )
    Horse.objects.filter(name="Pablo").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2019/03/IMG_36101-300x240.jpg"
    )
    Horse.objects.filter(name="Spirit").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2019/03/IMG_35801-300x244.jpg"
    )
    Horse.objects.filter(name="Lucky").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2019/03/IMG_35811-300x226.jpg"
    )
    Horse.objects.filter(name="Rascal").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2010/05/Rascal-300x300.jpg"
    )
    Horse.objects.filter(name="Pepper").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2019/03/IMG_35911-225x300.jpg"
    )
    Horse.objects.filter(name="Teka").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2010/05/Teka-300x226.jpg"
    )
    Horse.objects.filter(name="Cocoa").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2010/05/Cocoa-300x300.jpg"
    )
    Horse.objects.filter(name="Keebler").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2010/05/Keebler-283x300.jpg"
    )
    Horse.objects.filter(name="Domino").update(
        public_photo_url="http://www.holidayacresequestriancenter.com/wp-content/uploads/2019/03/received_1569916003199658-225x300.jpg"
    )


class Migration(migrations.Migration):

    dependencies = [("holiday_acres_api", "0014_auto_20220605_1431")]

    operations = [migrations.RunPython(associate_horse_photo)]
