version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
      - react
  django:
    container_name: django
    build:
      context: ./api
      dockerfile: ./Dockerfile
    command: poetry run python ./manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
  react:
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    command: yarn start
    ports:
      - 3000:3000
